apiVersion: compute-node.openstack.org/v1alpha1
kind: ComputeNodeOpenStack
metadata:
  name: worker-osp
  namespace: openstack
spec:
  # Add fields here
  roleName: worker-osp
  clusterName: ostest
  baseWorkerMachineSetName: ostest-worker-0
  workers: 1
  dedicated: true
  networkGateway: true
  selinuxDisabled: true
  compute:
    novaComputeCPUDedicatedSet: "4-7"
    novaComputeCPUSharedSet: "0-3"
    sshdPort: 2022
    commonConfigMap: common-config
    ospSecrets: osp-secrets
  network:
    nic: "enp6s0"
    bridgeMappings: "datacentre:br-ex"
    sriov:
      devName: "test"
  drain:
    drainPodImage: quay.io/openstack-k8s-operators/tripleo-deploy
    enabled: false
  openStackClientAdminSecret: openstackclient-admin
  openStackClientConfigMap: openstackclient
  serviceAccount: compute-node
