---
base_path: /home/ocp
#dev_scripts_repo: defaults to "https://github.com/openshift-metal3/dev-scripts.git"
#dev_scripts_branch: defaults to "HEAD"

# To set a specific release to install.
ocp_release_image: quay.io/openshift-release-dev/ocp-release:4.5.8-x86_64

# private repo to read required secret files from
# The playbooks expect secret files which can be placed in a private repo
# Right now these are:
# * rhel-subscription.yaml - content:
#   rhel_subscription_activation_key: <activation key>
#   rhel_subscription_org_id: "xxxxxxx"
# * pull-secret
#   obtain it from https://cloud.redhat.com/openshift/install/pull-secret
#secrets_repo: https uri to repo, no default manual local file is expected if not present
#secrets_branch: defaults to "HEAD"

# dev scripts switched to ipv6 per default, for now switch back
# https://github.com/openshift-metal3/dev-scripts/pull/969
ocp_ip_stack: v4

# size the OCP VM resources
ocp_num_masters: 3
# ocp_num_workers this needs to be > the number of osp compute workers
# worker-0 is used to host OSP controller VM, if osp_controller_scale set to 3 then worker-0 ..2 are used.
ocp_num_workers: 5
ocp_master_memory: 16384
ocp_master_vcpu: 8
ocp_master_disk: 120
ocp_storage_memory: 16384
ocp_storage_vcpu: 8
ocp_worker_memory: 8192
ocp_worker_vcpu: 4
ocp_worker_disk: 120

# list of workers that will be initially for ocp compute workers,
# will default to the last # of workers up to ocp_num_workers if unset
# E.g:
# ocp_compute_workers:
#   - worker-3

# OCP cluster name
ocp_cluster_name: ostest

# Released version of the opm package from the operator-framework
opm_version: v1.12.5

# operator github url where operators repos are underneath - default https://github.com/openstack-k8s-operators
#openstack_k8s_operators_https_url: defaults to "https://github.com/openstack-k8s-operators"
#openstack_k8s_operators_nova_branch: defaults to "HEAD"
#openstack_k8s_operators_neutron_branch: defaults to "HEAD"
#openstack_k8s_operators_keystone_branch: defaults to "HEAD"
#openstack_k8s_operators_heat_branch: defaults to "HEAD"

# operator images and tag to use
nova_operator_image: quay.io/openstack-k8s-operators/nova-operator:v0.0.5
neutron_operator_image: quay.io/openstack-k8s-operators/neutron-operator:v0.0.4
compute_node_operator_image: quay.io/openstack-k8s-operators/compute-node-operator:v0.0.5
cluster_operator_image: quay.io/openstack-k8s-operators/openstack-cluster-operator:v0.0.6
keystone_operator_image: quay.io/openstack-k8s-operators/keystone-operator:v0.0.6
mariadb_operator_image: quay.io/openstack-k8s-operators/mariadb-operator:v0.0.4
glance_operator_image: quay.io/openstack-k8s-operators/glance-operator:v0.0.3
placement_operator_image: quay.io/openstack-k8s-operators/placement-operator:v0.0.1
ovn_operator_image: quay.io/openstack-k8s-operators/ovn-operator:v0.0.1

# olm specific
csv_version: 0.0.1

ocp_network_type: OVNKubernetes

# Tempest
tempest_enabled: true

# tempest timeout in seconds
tempest_timeout: 3600

# tempest test whitelist, if [] smoke test runs
#tempest_whitelist: []
tempest_whitelist:
  - 'tempest.api.compute.servers.test_create_server.ServersTestJSON.test_list_servers'

local_working_dir: "~/{{ ocp_cluster_name }}-working"

# nfs export directory
nfs_data_dir: /home/nfs/data
nfs_export_dir: /home/nfs

default_timeout: 180

# worker node where openstackclient pod will run
openstackclient_pod_worker: worker-0

# ocs specific
ocs_enabled: false
ocs_worker_index: 1 # index of worker node where OCS cluster will be installed
ocs_worker_domain: "{{ ocp_cluster_name }}_worker_{{ ocs_worker_index }}"
ocs_worker_node: "worker-{{ ocs_worker_index }}"
ocs_data_dir: /home/ocs/data
ocs_disks:
  - vda
  #- vdb # uncomment for extra disks if desired
  #- vdc
ocs_disk_size: 200
ocs_full_cleanup: true # re-provisions the ocs_worker_node during clean-up to ensure a complete Ceph removal
