apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: &name nova-cell1-novncproxy
  namespace: openstack
  labels:
    app: *name
spec:
  host: nova-cell1-novncproxy.apps.ostest.test.metalkube.org
  path: /
  to:
    kind: Service
    name: *name
  port:
    targetPort: novncproxy
